f=open('Untitled-4.py','w')
(a,b,c)=(1,2,4)
s=input("Please enter your name:")
print('hello! ',s)
f.write(s)
f.write('\nprint(ok my name is  and i want to become )\n')
f.write('hello my name is rah\n')
f.write(str(a))
f.write(str(b))
f.write(str(c))
print('Content written in file')
f=open("Untitled-4.py",'r+')
a=f.read()
print(a)

f.close()